### ISSUE TITLE
Bounding undef-ness

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#10]
During the F2F last week, Philip raised the issue of how to bound the
variability of an undef value.  The troublesome scenario is:

        int i = some_undef_value();
        a[i];  // How to do the bounds check on this?

A naive translation including the bounds-check is:

        int i = some_undef_value();
        if (i < 0 || i >= a_bound) { return fail; }
        a[i];

But each use of an undef value can see a different concrete value, so
upon lowering to the machine and executing the code you could get the
following (uses of i mapping down to 12, 2, and 900 respectively):

        int i = undef;
        if (12 < 0 || 2 >= a_bound) { return fail; }
        a[900]; // Out of bounds!  You have been pown'd.

This is a good problem to solve.

The same problem occurs in digitial circuit design where a circuit block
needs to capture a digital signal from an asyncrhonous input.  You
want all uses within your block to use a consistent value (for a given
clock cycle).  The "undef" behaviour is analogous to sampling that
asynchronous signal at each *use* within your block, which leads to
inconsistent values due to differing signal propagation delays to reach
those uses.  The standard solution is to sample the asynchronous input
exactly once (with *one* register in the receiving clock domain), and
then distribute the output of that register to all intended uses within
your block.

(I'm skipping over the metastability management aspect to achieve a
target MTBF.  That's not relevant here.)

How does that translate back to the compiler-for-an-ISA domain?
The "undef" behaviour is supposed to give the compiler stack the
freedom to reuse registers for different program (SSA) values without
having to clear the register first or save/spill the register when no
longer needed.  The capture behaviour requires the whole compiler stack
to preserve the captured value either within a register or by spilling,
whatever is appropriate.

So, to safely do the bounds check on the array index, you have to
*capture* the index and use the same captured value for both the bounds
check *and* the access.  In our example, the compiler has to do something
like:

        int i = some_undef_value();
        int i_as_index = CAPTURE(i);  // A new compiler primitive.
        if (i_as_index < 0 || i_as_index >= a_bound) { return fail; }
        a[i_as_index];

The semantics of CAPTURE(x) is:

 - if x is undef, then result is some value for typeof(x).  The result
   value is not an undef value.  That is, all uses of the result will
   see the same value.  In concrete terms for common architectures, the
   value is preserved in a register or spilled as needed.

 - if x is not an undef, then the result is x.

Each implementation can have its own particular implementation of the CAPTURE
primitive.  For example, a crude one could be to map each instance of CAPTURE
to its own variable and executing CAPTURE(X) does a volatile store to the
variable, and uses of the value are volatile loads.

References

[1] "Synchronization in Digital Logic Circuits" (tutorial) Ryan Donohue.
https://web.stanford.edu/class/ee183/handouts/synchronization_pres.pdf

[2] Understanding Metastability in FPGAs (Intel Whitepaper).
https://www.intel.com/content/dam/www/programmable/us/en/pdfs/literature/wp/wp-01082-quartus-ii-metastability.pdf

**Comment by Kangz** [comment]
Just so I understand correctly, this isn't visible to the user but would be a primitive compilers would use internally? Also in SPIRV or WHLSL we should strive to have no UB except for data-races, so this would only be used for accesses that can be racy? At that point it looks a bit like the "volatile" keyword in C.

**Comment by dneto0** [comment]
> Just so I understand correctly, this isn't visible to the user but would be a primitive compilers would use internally?  

Yes.  

> Also in SPIRV or WHLSL we should strive to have no UB except for data-races, so this would only be used for accesses that can be racy?

To first order, yes.  But I'd like to think more carefully about it.

> At that point it looks a bit like the "volatile" keyword in C.

To first order, yes.  

The interesting bit is to avoid being too pessimistic.  You can pass _every_ value through the CAPTURE primitive, but that's too slow / too much.   It's best to minimize where you place these things while maintaining safety.  How well or easily that can be done depends strongly on language features and the execution environment.

To that end, I'd reference the security requirements as we determined previously (as far as I can tell) https://github.com/gpuweb/gpuweb/issues/39#issuecomment-344481628

**Comment by devshgraphicsprogramming** [comment]
I would personally overload the array accessor operator (pointers) and storage image acess with my own wrapper functions that would take the address/offset/coordinate by value/via copy (not reference).

SPIR-V has an actual memory model, compared to lets say DXIL/Metal, so preventing the compiler from optimizing should be easier than in a text-based shading language (otherwise you have to declare all resources that provide a pointer/texture coord as `volatile`)

**Comment by RobinMorisset** [comment]
This CAPTURE primitive matches the "freeze" primitive that folks have already been considering to add to LLVM for different reasons. See e.g.:
https://lists.llvm.org/pipermail/llvm-dev/2016-October/106182.html

I agree that any implementation will need something like it to deal with races.
