### ISSUE TITLE
Memory model

### ISSUE THREAD

**Issue by litherum** [gpuweb/WSL#11]
We should have something to say about the memory model

**Comment by dneto0** [comment]
I presented (most of) these slides at a recent WebGPU face-to-face meeting: [Slides](https://docs.google.com/presentation/d/1D2ZmqMa3GQJ13xcUMfaWmIJDv4AwZwUGB6fIoLLaCXQ/edit#slide=id.p55)

I argued:
- WebGPU should use a subset/simplification of the Vulkan memory model
- Short of that, use similar methodology as the Vulkan memory model:
   - Follow  [Wickerson et. al](https://johnwickerson.github.io/papers/memalloy.pdf)
   - Use [Alloy](http://alloy.lcs.mit.edu/alloy/) for formal modeling

**Comment by RobinMorisset** [comment]
Thank you very much for this pointer, I had missed the formal vulkan memory model.
I agree it sounds like a perfect starting point, I will have more to say once I take the time to study it in details.
