### ISSUE TITLE
Parse.consumeEndOfTypeArgs isn't testing rightShift

### ISSUE THREAD

**Issue by grorg** [gpuweb/WSL#225]
in Parse.consumeEndOfTypeArgs, the code

```
        if (rightShift)
            lexer.push(new LexerToken(lexer, rightShift, rightShift.index, rightShift.kind, ">"));
```

isn't covered by our tests.

**Comment by litherum** [comment]
We should use the Web Inspector’s code coverage view to find all the places our tests don’t test
