### ISSUE TITLE
WHLSL conversion to GLSL consideration

### ISSUE THREAD

**Issue by michaeltheory** [gpuweb/WSL#256]
Hey,

Just read the [awesome article on WHLSL](https://webkit.org/blog/8482/web-high-level-shading-language/) and am on board with an idea of a new shader language that targets multiple platforms.

However, the transition from WebGL to WebGPU is not going to be a clean break -- there is going to be a time where both must be targeted by the same project. Engines like three.js and Babylon will create separate renderers to render their abstract API, but the issue in that case is shaders. It will be impossible to build shaders twice, once in GLSL and once in WHLSL. 

I'm opening this ticket to start a discussion about allowing shaders written in WHLSL to be converted to GLSL for WebGL use.

**Comment by litherum** [comment]
Another idea that I've heard from readers is to add WHLSL support directly to WebGL. That wasn't a design goal of the language, but if there's enough support, we can see what would be required.

**Comment by michaeltheory** [comment]
@litherum The problem I see with that is it's yet another thing browsers would have to implement, compounding the initial problem of cross-browser support.
