### ISSUE TITLE
index.rst:  says a "file" must end with an End-Of-File token but doesn't say how it's spelled

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#259]
It says

> A valid file is made of a sequence of 0 or more top-level declarations, followed by the special End-Of-File token.

I think that "file" should be "translation unit" which appears earlier in index.rst. 

Unfortunately, that's the only mention of the End-Of-File token in the entire index.rst document.  It's not clear if the user must supply it and if so how to spell it.

**Comment by litherum** [comment]
WHLSL doesn't have files.

**Comment by dneto0** [comment]
index.rst says:

> A valid file is made of a sequence of 0 or more top-level declarations, followed by the special End-Of-File token.

In other parts of the document it talks about a "compilation unit".

I agree WHLSL should not have "files".   I'd be happy with "translation unit".  But the spec should use consistent terminology.
