### ISSUE TITLE
index.rst: entry point arguments: arrays are not allowed inside structs 

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#261]
It's an odd restriction.  Just an oversight?

**Comment by dneto0** [comment]
From  "Arguments and Return Types", in the bullet point for "Resources":

> Slices must only hold scalars, vectors, matrices, or structs containing any of these types. Nested structs are allowed. 

The array case is missing.

**Comment by litherum** [comment]
Yeah, we should treat them as resources, not stage in/out variables.

**Comment by dneto0** [comment]
>  We should write somewhere what happens if the WHLSL shader says the array has n elements but the API binds an array that has < n elements

Do you mean this at the outer level?  That is, where an API-side array is being bound to a slice that is an argument to an entry point?

Or do you mean an array inside a struct that is an argument to an entry point?   In this case I'm not sure how the API call can validate the array size because it's buried inside other data.
