### ISSUE TITLE
index.rst: stage in/out matching should ignore const'ness?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#262]
> Stage-out variables in a vertex shader are matched with stage-in variables in a fragment shader by semantic.
 After these stage-in/stage-out varaibles match, their qualified type must also match.

I would assume it should be ok to have 

     vertex void foo(  int : attribute(0) ) { ... }
     fragment void bar( const int : attribute(0)  ) { ... }

But that's disallowed by the spec.

**Comment by litherum** [comment]
Right now, WHLSL doesn't have the concept of const.
