### ISSUE TITLE
index.rst: stage out/in matching:  valid to have unfilled fragment inputs?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#263]
Is it ok for a fragment shader to have stage input variable at  attribute(3) but have no corresponding vertex stage output variable with attribute(3).   

The spec currently says

> After discovering all these matches, any other left-over variables are simply zero-filled.

So it's ok to have unmatched out/in variables on either side of the interface and those unmatched ones are zero-filled.  That seems inadvisable? 

Vulkan has more strict rules.  In particular, the user-defined interface variables must match Location and Component decorations (that's what corresponds to WHLSL's `attribute(k)`).   
See 14.1.3 Interface Matching, under https://www.khronos.org/registry/vulkan/specs/1.0/html/vkspec.html#interfaces-iointerfaces 

It's not clear to me that cases WHLSL's more relaxed rules permits cases which can be fixed up (worked around) for the Vulkan case.

**Comment by litherum** [comment]
Right. No matter which way the rules go on this issue, any implementation can fairly trivially fix up their implementation to match the rules. You're allowed to output things from a vertex shader that don't appear as inputs to the fragment shader, and the zero-filling is provided for symmetry here.

Why do you think it's valuable to modify the language to match Vulkan's rules?

**Comment by dneto0** [comment]
I wonder if there is a performance tradeoff to be concerned about?  It seems there would be two options: (1) fragment shader zero-fills all its input variables always, and (2) at pipeline construction time the API determines which fragment inputs are unmatched and then patches the fragment shader to zero-init those variables specifically.

I don't have a good sense of how much either case costs.  I'm told graphics folks are sensitive to any costs anywhere, so I think it's worth having the discussion of ease-of-use vs. potential cost.
