### ISSUE TITLE
Finish specifying stage in/out variables

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#264]
Section "Arguments and Return Types" discusses stage-in and stage-out variables.

It mixes discussion of both without saying where to find stage-in or stage-out variables.

I think the intent is to say a stage-out variable must: 
- be a scalar/vector/matrix variable
- be annotated with attribute(k) as a member of a struct type used in the return of the entry-point; or in the single-variable case have the attribute(k) semantic after the function signature but before the opening brace

I think the intent is to say a stage-in variable must:
- be a scalar/vector/matrix variable
- be in the argument list of the entry point
- be annotated with attribute(k)

The grammar permits any semantic on a variable declaration, anywhere. 
Can I add an attrbute(k) semantic to a variable declared in the body of a function?  That seems wrong somehow.

**Comment by litherum** [comment]
> The grammar permits any semantic on a variable declaration, anywhere.

Not on any variable declaration. But it can be on any function parameter or struct member. However, the spec also says that if a semantic exists on something that isn't an argument / return value of an entry point, it is ignored.

**Comment by litherum** [comment]
The spec says:

> See below for a rigorous definition of "match."

But then doesn't include that. We need to include it.
