### ISSUE TITLE
index.rst: missing rules for stage-in and stage-out variables with conflicting index

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#265]
I think it should be invalid to say:

vertex int foo(int a : attribute(0), int b : attribute(0))  : attribute(0) { return 0; }

I think that would be wrong because of the duplicate attribute index on parameters a and b.  I didn't see anything in the spec about that.

Similarly, this should be invalid too:

struct Out {
  int a : attribute(0);
  int b : attribute(0); // conflict error?
}

vertex Out foo(...) { ... }

**Comment by litherum** [comment]
Yeah, we should just disallow duplicates.

We should also consider not allowing the same resource to be bound to two different binding points.

**Comment by dneto0** [comment]
> We should also consider not allowing the same resource to be bound to two different binding points.

Yeah, that's a issue to resolve at the API level.  Vulkan deliberately specifies that that is possible, and has rules about what synchronizations (and format translations) are required to avoid races.
