### ISSUE TITLE
Redesign specialization constants

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#267]
In the "Arguments and Return Types" section, it says that one class of argument are specialization constants.

> 4. Specialization constants. These are scalar variables which must be specified by the WebGPU API before the shader is allowed to execute. These variables must use the `specialized` semantic.

Later, the spec says `specialized` is a keyword of the language.

That's all  the info in index.rst.

The grammar lists `specialized` as an available semantic.  It does not take a parameter like `attribute` does.

So it seems:

- any variable anywhere can have the `specialized` semantic on it.
- such variables are not distinguished from each other
- such variables are mutable

This does not match reality.   

In Vulkan (and the GLSL dialect for Vulkan) each specialization constant is associated with an integer index, so you can tell them apart.  In the SPIR-V module, the specialization constant is an OpSpecConstant with a SpecId decoration to give it its index.  So the value is treated as a constant at pipeline creation time.

**Comment by dneto0** [comment]
Ok, one of my objections is answered

> When not in the context of arguments or return values of entry points, semantics are ignored.

So that crosses off "any variable anywhere can have the specialized semantic on it" as an issue.  It might be confusing, but valid to do that in a program.

**Comment by kainino0x** [comment]
3b. The way this concept is described, it allows the hardware to "prefetch", but the value is set happen after compilation of the program so it can't be used in (e.g.) constant folding and dead branch elimination. So I think it's a distinct concept (not sure if it has an equivalent in other APIs).

**Comment by dneto0** [comment]
There's already prior art for HLSL and Vulkan-style specialization constants.
See the docs for the SPIR-V backend to DXC: https://github.com/Microsoft/DirectXShaderCompiler/blob/master/docs/SPIR-V.rst#specialization-constants
