### ISSUE TITLE
index.rst: entry point arguments are not distinguished by order or position?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#270]
The section on  _Entry Points -> Arguments and return_ types says:

> Arguments to entry points are not distinguished by position or order. 

That begs the question: how are arguments distinguished?  And to whom?

Reading between the lines, I think this is trying to talk about is that when the API side is setting up a pipeline to invoke the entry point, it has to map parameter values to entry point arguments.  And the question is how to identify the entry point arguments so that you can map values to them.

I looked but didn't see how to do this in WHLSL.   But that sentence does say it's not done by position or order.
So in the following:

     vertex void foo(int A, int B)

How does the API side set parameters A and B, distinguishing between the two?

**Comment by litherum** [comment]
Right, this section probably needs some more editorial.
