### ISSUE TITLE
modf is specified incorrectly

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#272]
See https://github.com/gpuweb/WHLSL/blob/master/Spec/source/Generate_Standard_Library.js#L1311 

The essence is to use uint to get the integer part of a float.
```
    for (let type of [`half`, `float`]) {
        print(`${type} modf(${type} x, ${addressSpace} ${type}* ip) {`);
        print(`    uint result = uint(x);`);
        print(`    if (ip != null)`);
        print(`        *ip = x - ${type}(result);`);
        print(`    return ${type}(result);`);
        print(`}`);
```

First, it should use trunc instead.

Second, the return value should be the fractional part, and the `ip` should have the integer part.

**Comment by litherum** [comment]
Why do you think that it's incorrect? Maybe I wrote it exactly as I intended! (I didn't)

At some point I need to do a pass to make sure all the standard library functions match HLSL. It's pretty low priority, though.
