### ISSUE TITLE
Use more friendly names for semantics

### ISSUE THREAD

**Issue by grorg** [gpuweb/WSL#281]
Some of the semantic names come from HLSL. I suggest we keep them as aliases for compatibility, but the official names move to something more friendly.

e.g. instead of `SV_Position`, we accept `position`

similarly

`SV_Target0` becomes `target(0)`
`SV_VertexID` becomes `vertex_id`

and so on.

**Comment by litherum** [comment]
I'm all for more friendly names.

My research on HLSL compatibility shows that these semantics seem to be arbitrary; a user can put any string they want in there and the compiler will use it. It seems like the arbitrary names are relevant to attributes, where data flows into and out of each shader stage - I expect that these arbitrary strings get matched between the vertex and fragment stages.  This seems to explain why the built-in names start with "SV_" - prefixing with "SV_" creates a namespace where the user can't supply names.

I hope we can find some sort of middle ground between the two models, though. We would have to think of a proposal for how they're going to work.

**Comment by grorg** [comment]
We have:

```
SV_InstanceID
SV_VertexID
PSIZE
SV_Position
SV_IsFrontFace
SV_SampleIndex
SV_InnerCoverage
SV_Target
SV_Depth
SV_Coverage
SV_DispatchThreadID
SV_GroupID
SV_GroupIndex
SV_GroupThreadID
```

I wonder how many of the arbitrary names in use would be conflicting with things like "position".
