### ISSUE TITLE
Reference implementation allows whitespace between "operator" and the operator name

### ISSUE THREAD

**Issue by litherum** [gpuweb/WSL#289]
It parses things like 
```WHLSL
int operator +(int, int)
```

However, the grammar treats `operator+` as a token, so no whitespace is allowed inside it.

**Comment by ndugger** [comment]
Even in my C++, I prefer a whitespace between `operator` and the name. If it's not too much trouble, I think explicitly allowing a whitespace character there would be great.

**Comment by RobinMorisset** [comment]
Yes, I think it was a mistake on my side when writing the spec (I did not know a space is allowed in this position even in C++). I will try to fix it in both the spec and the WIP C++ implementation.
