### ISSUE TITLE
WHLSL.ott missing rules for arithmetic expressions?

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#294]
I couldn't find any rules for normal arithmetic such as + - * /

I would have expected it in the section {{com Small-step reduction on expressions}}:
https://github.com/gpuweb/WHLSL/blob/master/Spec/WHLSL.ott#L615

**Comment by RobinMorisset** [comment]
I am planning to put it in the standard library section (since these are just normal operators that happen to be declared in the standard library). I agree that we must write something about them, at least to discuss what happens in case of an overflow.

**Comment by dneto0** [comment]
Yes, I was actually intrested in the behaviour of   (INT_MIN / -1)  which overflows

**Comment by RobinMorisset** [comment]
I'll try to write that section this evening or tomorrow. The short of it is that we plan to allow a few different behaviors by implementations, including trapping and computing the overflow in 2's complement.

**Comment by dneto0** [comment]
Some hardware saturates, i.e. produces MAX_INT    :-(

**Comment by RobinMorisset** [comment]
That kind of thing is definitely something I need to check before writing that section, our intent is to allow every behavior that can actually occur in hardware.
