### ISSUE TITLE
desugaring != via negation of == does the wrong thing for floating point

### ISSUE THREAD

**Issue by dneto0** [gpuweb/WSL#295]
Currently, a != expression is desugared via ==

See https://github.com/gpuweb/WHLSL/blob/master/Spec/WHLSL.ott#L286 
```
e --> e' :: :: desugaring_expr :: '' {{com Desugaring expressions}} by
    
    ----------------------- :: not_equals_operator
    e != e' --> ! (e == e')
```

If f and g are floating point values, then  

     f != g

is not the same as 

    ! (f == g)

That's because NaNs are treated differently in the two expressions.

See the "ordered" and "unordered" variants of fcmp in LLVM IR, or the FOrd* vs. FUnord* instructions in SPIR-V.

**Comment by RobinMorisset** [comment]
Good catch, this is indeed an issue we had missed.
We'll fix both the spec and the reference implementation.

**Comment by RobinMorisset** [comment]
The spec has been fixed, the reference Implementation (and the WIP C++ implementation) have not been fixed yet.
