### ISSUE TITLE
Do-while validation rules are a little overzealous

### ISSUE THREAD

**Issue by litherum** [gpuweb/WSL#314]
> To check a do-while statement:
> 
> Check that the condition is well-typed, of type bool
> Check that the body of the loop is a well-typed statement whose behaviours we will call B
> Check that B does not contain a return of a pointer type, or of an array reference type
> Make a new set of behaviours from B by removing Break and Continue (if they are present) and adding Nothing
> Then the do-while statement is well-typed, and its behaviours is this new set

Consider the following case:
```
int foo() {
  do {
    return 42;
  } while (true);
}
```

The rules say that this snippet would be an error, but it probably shouldn't be.

It should probably add Nothing only conditionally, perhaps if the result after removing Break and Continue is the empty set.

**Comment by litherum** [comment]
Switch statements have this problem, too.

**Comment by RobinMorisset** [comment]
Looking at it, there is a much more serious problem with switch statements: it is a soundness problem, we currently allow Fallthrough in the last case (with unclear semantics).
I will fix that, but it probably deserves another ticket.

You are right that we can also modify the rule to only add Nothing when there is a Break somewhere in the switch.

**Comment by RobinMorisset** [comment]
I've fixed both of these problems in index.rst, but not yet in ott, nor in either of the implementations.

**Comment by JusSn** [comment]
Example of invalid switch statement according to these rules that I just ran into when debugging the compiler:

`    
switch (id) {
    case 0:
        return float4(-1, 1, 0, 1);
    case 1:
        return float4(-1, -1, 0, 1);
    case 2:
        return float4(1, 1, 0, 1);
    default:
        return float4(1, -1, 0, 1);
    }
`

**Comment by RobinMorisset** [comment]
In the case of Loops, it turns out that even Continue being removed can require Nothing to be added. Consider the following example:
x = true;
while (x) {
    x = false;
    continue;
}
The control-flow can obviously exit this loop, so the behavior must get Nothing. I will fix the Ott and index.rst.
