### ISSUE TITLE
Implement isnormal

### ISSUE THREAD

**Issue by litherum** [gpuweb/WSL#35]
Migrated from https://bugs.webkit.org/show_bug.cgi?id=189596:

At 2018-09-13T18:39:04Z, tdenney@apple.com wrote:
These functions are currently unimplemented in Intrinsics.

**Comment by litherum** [comment]
At 2018-09-21T22:33:25Z, tdenney@apple.com wrote:
Created attachment 350443
WIP

**Comment by litherum** [comment]
At 2018-09-21T22:35:01Z, tdenney@apple.com wrote:
Created attachment 350444
WIP

**Comment by litherum** [comment]
At 2018-09-22T08:55:37Z, mmaxfield@apple.com wrote:
Comment on attachment 350444
WIP

View in context: https://bugs.webkit.org/attachment.cgi?id=350444&action=review

> Tools/WebGPUShadingLanguageRI/Intrinsics.js:757
> +                    EPtr.box(!Number.isNaN(value.loadValue()));

Nope. "normal" means both not nan and not denormalized

> Tools/WebGPUShadingLanguageRI/Intrinsics.js:808
> +                    EPtr.box(castToFloat(bitwiseCast(Float32Array, Uint32Array, value.loadValue() & 0xFF)));

We have to do more bit twiddling for this one.

> Tools/WebGPUShadingLanguageRI/Intrinsics.js:815
> +                    EPtr.box(bitwiseCast(Uint32Array, Float32Array, castToHalf(value.loadValue())) & 0xFF);

Ditto

**Comment by RobinMorisset** [comment]
f16 is no longer in the language
