### ISSUE TITLE
Delete the "restricted" keyword

### ISSUE THREAD

**Issue by litherum** [gpuweb/WSL#53]
Migrated from https://bugs.webkit.org/show_bug.cgi?id=189131:

At 2018-08-30T00:04:59Z, mmaxfield@apple.com wrote:
We don't need it any more.

**Comment by litherum** [comment]
At 2018-08-30T00:05:16Z, mmaxfield@apple.com wrote:
*** Bug 176580 has been marked as a duplicate of this bug. ***

**Comment by RobinMorisset** [comment]
It is still marked in the grammar as a "Reserved for future use", along with things like "const" or "uniform". I would like to keep it for now, it is just 5 lines in the lexer.
